

# NumPy exercises


In [2]:
# Import the numpy package under the name np
import numpy as np
import sys

# Print the numpy version and the configuration
print(np.__version__)

1.20.3


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [3]:
# your code goes here
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [4]:
# your code goes here
b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [6]:
# your code goes here
c = np.ones([2,2], dtype=int)
print(c)

[[1 1]
 [1 1]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [7]:
# your code goes here
d = np.ones([3,2], dtype = float)
print(d)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [8]:
x = np.arange(4, dtype=int)

e = np.ones_like(X)

print(x)
print(e)


[0 1 2 3]
[1 1 1 1]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [9]:
# your code goes here
x = np.array([[1,2,3,4], [4,5,6,7]], dtype = int)
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [11]:
# your code goes here
np.ones([4,4], dtype=int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [12]:
# your code goes here
x = np.array([[1,3,5], [4,5,5]], dtype = int)
np.ones_like(x) * 7

array([[7, 7, 7],
       [7, 7, 7]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [13]:
# your code goes here
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [15]:
# your code goes here
np.random.randint(1, 5, size=4)
#numpy.random.randint(low, high=None, size=None, dtype=’l’)

array([1, 2, 1, 2])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [17]:
# your code goes here
np.random.randn(3,3,3)

array([[[ 0.84938339, -0.65648814,  1.83654277],
        [-1.17443431,  0.45545698,  0.33668564],
        [-0.40601482, -1.34497323,  0.32776954]],

       [[-0.19677651, -1.34315601, -0.78073011],
        [ 1.58032536, -0.53923977,  1.27575457],
        [ 0.40543122,  1.70999397, -1.83351127]],

       [[-0.04265123,  0.93844767,  1.73598104],
        [-0.77025887, -0.21676464, -0.71663971],
        [ 0.45183762,  1.12896129,  2.27124337]]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [19]:
# your code goes here
x = [1, 2, 3, 4, 5, 6]
print(x, type(x), sys.getsizeof(x))

y = np.array(x)
print(y, type(y), (y.size * y.itemsize)) # different type
#as you can see, a python list with the same number of element consumes memory 6.3 times more than the numpy array

[1, 2, 3, 4, 5, 6] <class 'list'> 152
[1 2 3 4 5 6] <class 'numpy.ndarray'> 24


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [21]:
# your code goes here
x = np.array([[1,2,3],[4,5,6]], dtype = int)
print(x)
print(type(x))
y = np.copy(x)
print(y)
print(type(y))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

In [22]:
# your code goes here
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

In [24]:
# your code goes here
np.arange(3, 16, 3)

array([ 3,  6,  9, 12, 15])

In [25]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

In [26]:
# your code goes here
np.arange(1, 20)[::-2]

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [27]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [28]:
# your code goes here
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [29]:
np.arange(1,7).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

In [30]:
# your code goes here
a=np.array([1])
print(a.size*a.itemsize, 'bytes', 'for', len(a), 'element of a numpy array')

4 bytes for 1 element of a numpy array


In [31]:
b=[1]
print(sys.getsizeof(b), 'bytes', 'for', len(b), 'element of a python list')

64 bytes for 1 element of a python list


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's sixth element

In [32]:
# your code goes here
x = np.arange(1, 21)
print(a)
x[5]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


6

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

In [33]:
# your code goes here
x[-1]

20

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

In [34]:
# your code goes here
x[:3]

array([1, 2, 3])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements

In [35]:
# your code goes here
x[1:-1]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [36]:
# your code goes here
x[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [37]:
x[::-3]

array([20, 17, 14, 11,  8,  5,  2])

In [38]:
x[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

In [39]:
# your code goes here
x = np.array(
    [[0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9],
    [10, 11, 12, 13, 14],
    [15, 16, 17, 18, 19],
    [20, 21, 22, 23, 24]]
)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
x[0]

array([0, 1, 2, 3, 4])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [41]:
# your code goes here
x[-1]

array([20, 21, 22, 23, 24])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [42]:
# your code goes here
x[0][0]

0

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [43]:
# your code goes here
x[-1][-1]

24

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [44]:
# your code goes here
x[1][-1]

9

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [45]:
# your code goes here
x[:2, :2]

array([[0, 1],
       [5, 6]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [62]:
# your code goes here
print(x)
x[3:, 3:]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 1  1  1  1  0]]


array([[18, 19],
       [ 1,  0]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [47]:
# your code goes here
np.array(x, float)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [71]:
#X = [-5, -3, 0, 10, 40]
print(type(x))
print(x.dtype)
print(x)
y = np.array(x, float)
print(y.dtype)
print(y)


<class 'numpy.ndarray'>
int32
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 1  1  1  1  0]]
float64
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [ 1.  1.  1.  1.  0.]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [49]:
# your code goes here
x[::-1]

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [50]:
# your code goes here
y = np.random.randint(0, 24, size=(5,5))
print('array before sorting :')
print(y)
print('array after sorting :')
y.sort()
print(y)

array before sorting :
[[17  5  9 19  2]
 [ 1  0  1 10  4]
 [14 10  6  5 21]
 [15  5 18 12  1]
 [ 7  9 17  8  9]]
array after sorting :
[[ 2  5  9 17 19]
 [ 0  1  1  4 10]
 [ 5  6 10 14 21]
 [ 1  5 12 15 18]
 [ 7  8  9  9 17]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

In [51]:
# your code goes here
x =  [21, 37, 15, 50, 60, 99]
print(c)
x[3] = 40
print(c)

[21, 37, 15, 50, 60, 99]
[21, 37, 15, 40, 60, 99]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [52]:
# your code goes here
print(x)
x[-1]=1
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 1  1  1  1  1]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [53]:
# your code goes here
print(x)
x[-1][-1]=0
print('\n')
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 1  1  1  1  1]]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 1  1  1  1  0]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [72]:
# your code goes here
print(x)
print('\n')
x+5
print(x)
y = x+5
print('\n')
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 1  1  1  1  0]]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 1  1  1  1  0]]


[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [ 6  6  6  6  5]]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [55]:
# your code goes here
x = np.random.randint(-10, 10, size=10)
print(x,'\n')
z = x <= 0  
print(z)

[  9   9   3  -1 -10   3  -5   0   4   5] 

[False False False  True  True False  True  True False False]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get the negative elements

In [56]:
# your code goes here
x[x<=0]

array([ -1, -10,  -5,   0])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [57]:
# your code goes here
x[x>5]

array([9, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [58]:
# your code goes here
avg = x.mean()
print('average : ', avg)
more_than_avg = x[x > avg]
print(more_than_avg)

average :  1.7
[9 9 3 3 4 5]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [59]:
# your code goes here
x = np.arange(15)
x[(t==2) | (x==10)]

array([ 2, 10])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if all elements is true

In [60]:
# your code goes here
x = np.array([1,1,1,1,1])
x.all()

True

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is true

In [73]:
# your code goes here
x = np.array([1,1,0,0])
x.any()

True

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [ ]:
# your code goes here
print(x,'\n')
print('sum of all elements : ', y.sum())

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements

In [ ]:
# your code goes here
print(x,'\n')
print('mean : ', y.mean())

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

In [ ]:
# your code goes here
print(x,'\n')
print('sum per column (vertical)')
print(x.sum(axis=0)) # remember: axis=0 columns; axis=1 rows
print('sum per row (horizontal)')
print(x.sum(axis=1))

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its columns and rows

In [ ]:
# your code goes here
print(x)
print('\n mean value per columns (vertical):')
print(x.mean(axis=0))
print('\n mean value per rows (horizontal):')
print(x.mean(axis=1))


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [ ]:
# your code goes here
print(x)
print('\n max value : ')
print(x.max())

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)